name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-18.04
    container: ubuntu:18.04

    steps:
    - uses: actions/checkout@v2
    - name: Checkout Suricata
      uses: actions/checkout@v2
      with:
        repository: dbcfd/suricata
        path: suricata
        ref: sensicata
    - name: Checkout libhtp
      uses: actions/checkout@v2
      with:
        repository: OISF/libhtp
        path: suricata/libhtp
    - name: Install Required libraries
      run: |
        apt-get update
        apt-get install -y \
          curl \
          build-essential \
          autoconf \
          automake \
          make \
          gcc \
          pkg-config \
          git \
          libtool \
          libpcre3 \
          libpcre3-dev \
          libpcap-dev \
          libnet1-dev \
          libyaml-0-2 \
          libyaml-dev \
          libmagic-dev \
          libjansson-dev \
          zlib1g \
          zlib1g-dev
    - name: Install rust
      run: |
        curl https://sh.rustup.rs -sSf | sh -s -- -y
    - name: Add Rust to Path
      run: echo "$HOME/.cargo/bin" >> $GITHUB_PATH
    - name: Add Rust Tools
      run: |
        rustup component add rustfmt
        cargo install --force cbindgen
    - name: Build Suricata
      working-directory: suricata
      run: |
        autoreconf -i
        ./configure --with-unix-socket
        make install
        make install-conf
    - name: Format
      run: cargo fmt --all -- --check
    - name: Build
      run: cargo build --verbose
    #- name: Run tests
    #  run: RUST_LOG=debug SURICATA_EXE=/usr/local/bin/suricata SURICATA_CONFIG_DIR=/usr/local/etc/suricata SURICATA_LOG_DIR=/tmp SC_LOG_LEVEL=info cargo test --package suricata-ipc --verbose
